name: Delivery and Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Semantic Versioning
        uses: anitvam/conventionalcommit-semantic-releasing@v0.3.6
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Get tag
        run: git describe --tags --abbrev=0